backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://psychmind.netlify.app

collections:
  - name: "poems"
    label: "Poems"
    folder: "content/poems"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Poem Content", name: "body", widget: "markdown"}

  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Story Cover", name: "thumbnail", widget: "image", required: false}
      - {label: "Story Content", name: "body", widget: "markdown"}

  - name: "psychology"
    label: "Psychology"
    folder: "content/psychology"
    create: true
    slug: "{{slug}}"
    format: "frontmatter"
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Article Content", name: "body", widget: "markdown"}
